import type { SourceLangCode, TargetLangCode } from '../services/palabra/types';

export interface LangOption<T> {
  id: T;
  label: string;
  code: string;
}

export const SOURCE_LANGS: LangOption<SourceLangCode>[] = [
  { id: 'auto', label: 'Auto Detect', code: 'AUTO' },
  { id: 'ar', label: 'Arabic', code: 'AR' },
  { id: 'be', label: 'Belarusian', code: 'BE' },
  { id: 'bg', label: 'Bulgarian', code: 'BG' },
  { id: 'ca', label: 'Catalan', code: 'CA' },
  { id: 'cs', label: 'Czech', code: 'CS' },
  { id: 'cy', label: 'Welsh', code: 'CY' },
  { id: 'da', label: 'Danish', code: 'DA' },
  { id: 'de', label: 'German', code: 'DE' },
  { id: 'el', label: 'Greek', code: 'EL' },
  { id: 'en', label: 'English', code: 'EN' },
  { id: 'es', label: 'Spanish', code: 'ES' },
  { id: 'et', label: 'Estonian', code: 'ET' },
  { id: 'fi', label: 'Finnish', code: 'FI' },
  { id: 'fr', label: 'French', code: 'FR' },
  { id: 'gl', label: 'Galician', code: 'GL' },
  { id: 'he', label: 'Hebrew', code: 'HE' },
  { id: 'hi', label: 'Hindi', code: 'HI' },
  { id: 'hr', label: 'Croatian', code: 'HR' },
  { id: 'hu', label: 'Hungarian', code: 'HU' },
  { id: 'id', label: 'Indonesian', code: 'ID' },
  { id: 'it', label: 'Italian', code: 'IT' },
  { id: 'ja', label: 'Japanese', code: 'JA' },
  { id: 'ko', label: 'Korean', code: 'KO' },
  { id: 'lt', label: 'Lithuanian', code: 'LT' },
  { id: 'lv', label: 'Latvian', code: 'LV' },
  { id: 'ms', label: 'Malay', code: 'MS' },
  { id: 'nl', label: 'Dutch', code: 'NL' },
  { id: 'no', label: 'Norwegian', code: 'NO' },
  { id: 'pl', label: 'Polish', code: 'PL' },
  { id: 'pt', label: 'Portuguese', code: 'PT' },
  { id: 'ro', label: 'Romanian', code: 'RO' },
  { id: 'ru', label: 'Russian', code: 'RU' },
  { id: 'sk', label: 'Slovak', code: 'SK' },
  { id: 'sl', label: 'Slovenian', code: 'SL' },
  { id: 'sv', label: 'Swedish', code: 'SV' },
  { id: 'sw', label: 'Swahili', code: 'SW' },
  { id: 'ta', label: 'Tamil', code: 'TA' },
  { id: 'th', label: 'Thai', code: 'TH' },
  { id: 'tr', label: 'Turkish', code: 'TR' },
  { id: 'uk', label: 'Ukrainian', code: 'UK' },
  { id: 'ur', label: 'Urdu', code: 'UR' },
  { id: 'vi', label: 'Vietnamese', code: 'VI' },
  { id: 'zh', label: 'Chinese (Simplified)', code: 'ZH' },
];

export const TARGET_LANGS: LangOption<TargetLangCode>[] = [
  { id: 'ar-sa', label: 'Arabic', code: 'AR' },
  { id: 'be', label: 'Belarusian', code: 'BE' },
  { id: 'bg', label: 'Bulgarian', code: 'BG' },
  { id: 'ca', label: 'Catalan', code: 'CA' },
  { id: 'cs', label: 'Czech', code: 'CS' },
  { id: 'cy', label: 'Welsh', code: 'CY' },
  { id: 'da', label: 'Danish', code: 'DA' },
  { id: 'de', label: 'German', code: 'DE' },
  { id: 'el', label: 'Greek', code: 'EL' },
  { id: 'en-us', label: 'English (US)', code: 'US' },
  { id: 'en-gb', label: 'English (UK)', code: 'GB' },
  { id: 'es', label: 'Spanish', code: 'ES' },
  { id: 'es-mx', label: 'Spanish (Mexico)', code: 'MX' },
  { id: 'et', label: 'Estonian', code: 'ET' },
  { id: 'fi', label: 'Finnish', code: 'FI' },
  { id: 'fr', label: 'French', code: 'FR' },
  { id: 'fr-ca', label: 'French (Canada)', code: 'CA' },
  { id: 'gl', label: 'Galician', code: 'GL' },
  { id: 'he', label: 'Hebrew', code: 'HE' },
  { id: 'hi', label: 'Hindi', code: 'HI' },
  { id: 'hr', label: 'Croatian', code: 'HR' },
  { id: 'hu', label: 'Hungarian', code: 'HU' },
  { id: 'id', label: 'Indonesian', code: 'ID' },
  { id: 'it', label: 'Italian', code: 'IT' },
  { id: 'ja', label: 'Japanese', code: 'JA' },
  { id: 'ko', label: 'Korean', code: 'KO' },
  { id: 'lt', label: 'Lithuanian', code: 'LT' },
  { id: 'lv', label: 'Latvian', code: 'LV' },
  { id: 'ms', label: 'Malay', code: 'MS' },
  { id: 'nl', label: 'Dutch', code: 'NL' },
  { id: 'no', label: 'Norwegian', code: 'NO' },
  { id: 'pl', label: 'Polish', code: 'PL' },
  { id: 'pt-br', label: 'Portuguese (Brazil)', code: 'BR' },
  { id: 'pt-pt', label: 'Portuguese', code: 'PT' },
  { id: 'ro', label: 'Romanian', code: 'RO' },
  { id: 'ru', label: 'Russian', code: 'RU' },
  { id: 'sk', label: 'Slovak', code: 'SK' },
  { id: 'sl', label: 'Slovenian', code: 'SL' },
  { id: 'sv', label: 'Swedish', code: 'SV' },
  { id: 'sw', label: 'Swahili', code: 'SW' },
  { id: 'ta', label: 'Tamil', code: 'TA' },
  { id: 'th', label: 'Thai', code: 'TH' },
  { id: 'tr', label: 'Turkish', code: 'TR' },
  { id: 'uk', label: 'Ukrainian', code: 'UK' },
  { id: 'ur', label: 'Urdu', code: 'UR' },
  { id: 'vi', label: 'Vietnamese', code: 'VI' },
  { id: 'zh', label: 'Chinese (Simplified)', code: 'ZH' },
  { id: 'zh-tw', label: 'Chinese (Traditional)', code: 'TW' },
];

export const getSourceLabel = (id: SourceLangCode): string => {
  return SOURCE_LANGS.find((l) => l.id === id)?.label || id;
};

export const getTargetLabel = (id: TargetLangCode): string => {
  return TARGET_LANGS.find((l) => l.id === id)?.label || id;
};
